name: Playwright Tests
on:                               # Визначає події, які тригерять цей workflow
  push:                           # workflow буде запускатися щоразу, коли відбувається пуш
    branches: [ main, master ]  
  #pull_request:
    #branches: [ main, master ]
  # schedule:
  # - cron: "30 14 * * *"
  
jobs:
  test:
    timeout-minutes: 60            # Ліміт часу на виконання задачі. Якщо тест займе більше ніж 60 хвилин, він буде зупинений.
    runs-on: ubuntu-latest         #  в якому середовищі буде виконуватись 
    
    steps:
    - uses: actions/checkout@v4    # використовує офіційну GitHub Action для того, щоб завантажити код репозиторію у віртуальне середовище, де буде виконуватися тест.
    - uses: actions/setup-node@v4  # налаштовує середовище Node.js.
      with:
        node-version: lts/*
    - name: Install dependencies
        run: npm ci       # щоб бралися з кешу, що і в package.json, але якщо хочемо щоб кожного разу установлювались нові версії пакетів, то тоді варто прописати npm i           
    - name: Install Playwright Browsers 
        run: npx playwright install --with-deps
    - name: Run Playwright tests
        run: npm run test # було npx playwright test, але я заповнила згідно скріпта у package.json
    - uses: actions/upload-artifact@v4  # використовує GitHub Action для завантаження артефактів (результатів роботи, звітів і т.д.) у GitHub.
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
